package com;


/**
* com/HelloWorld.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HelloWorld.idl
* Sunday, May 24, 2026 8:28:35 AM IST
*/

public interface HelloWorld extends HelloWorldOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HelloWorld
