package BankingApp;


/**
* BankingApp/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Wednesday, May 27, 2026 9:24:21 AM IST
*/

public interface AccountOperations 
{
  double getBalance (String accNo);
  void deposit (String accNo, double amount);
  void withdraw (String accNo, double amount) throws BankingApp.InsufficientBalance;
} // interface AccountOperations
