package BankingApp;


/**
* BankingApp/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Wednesday, May 27, 2026 9:24:21 AM IST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
