package TestApp;


/**
* TestApp/TestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./TestApp.idl
* Sunday, May 24, 2026 7:57:57 AM IST
*/

public interface TestOperations 
{
  void m ();
} // interface TestOperations
