package TestApp;


/**
* TestApp/TestPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./TestApp.idl
* Sunday, May 24, 2026 7:57:57 AM IST
*/

public abstract class TestPOA extends org.omg.PortableServer.Servant
 implements TestApp.TestOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("m", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TestApp/Test/m
       {
         this.m ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TestApp/Test:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Test _this() 
  {
    return TestHelper.narrow(
    super._this_object());
  }

  public Test _this(org.omg.CORBA.ORB orb) 
  {
    return TestHelper.narrow(
    super._this_object(orb));
  }


} // class TestPOA
