package TestApp;


/**
* TestApp/TestHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./TestApp.idl
* Sunday, May 24, 2026 7:57:57 AM IST
*/

abstract public class TestHelper
{
  private static String  _id = "IDL:TestApp/Test:1.0";

  public static void insert (org.omg.CORBA.Any a, TestApp.Test that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TestApp.Test extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TestApp.TestHelper.id (), "Test");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TestApp.Test read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TestStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TestApp.Test value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TestApp.Test narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestApp.Test)
      return (TestApp.Test)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestApp._TestStub stub = new TestApp._TestStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TestApp.Test unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestApp.Test)
      return (TestApp.Test)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestApp._TestStub stub = new TestApp._TestStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
