package TestApp;

/**
* TestApp/TestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./TestApp.idl
* Sunday, May 24, 2026 7:57:57 AM IST
*/

public final class TestHolder implements org.omg.CORBA.portable.Streamable
{
  public TestApp.Test value = null;

  public TestHolder ()
  {
  }

  public TestHolder (TestApp.Test initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestApp.TestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestApp.TestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestApp.TestHelper.type ();
  }

}
